### ISSUE TITLE
请问Expert Identity是只在训练数据中加入吗？还是说在测试数据中也加入了Expert Identity？

### ISSUE THREAD

**Issue by xyfZzz** [OFA-Sys/ExpertLLaMA#1]
请问Expert Identity是只在训练数据中加入吗？还是说在测试数据中也加入了Expert Identity？

**Comment by BenfengXu** [comment]
ExpertPrompting是一种推理增强的方法，只在inference阶段使用。
我们使用这一方法，基于GPT-3.5接口生产了对应Alpaca Instruction的Expert数据（答案）。
在数据生产完成后，ExpertLLaMA的训练和测试阶段，均只使用这些答案，与Identity无关~

**Comment by xyfZzz** [comment]
> ExpertPrompting是一种推理增强的方法，只在inference阶段使用。 我们使用这一方法，基于GPT-3.5接口生产了对应Alpaca Instruction的Expert数据（答案）。 在数据生产完成后，ExpertLLaMA的训练和测试阶段，均只使用这些答案，与Identity无关~

好的，谢谢！
